module.exports = {
  apps: [{
    name: 'healthapp-backend',
    script: 'src/index.ts',
    interpreter: 'npx',
    interpreter_args: 'tsx',
    cwd: __dirname,
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      PORT: 3001,
    },
    env_file: '.env',
    max_memory_restart: '500M',
    error_file: './logs/pm2-error.log',
    out_file: './logs/pm2-out.log',
    log_file: './logs/pm2-combined.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    max_size: '10M',
    retain: 7,
    autorestart: true,
    watch: false,
    restart_delay: 3000,
    max_restarts: 10,
    kill_timeout: 5000,
    listen_timeout: 10000,
    shutdown_with_message: true,
  }],
};
