import { getDb, closeDb } from '../config/database';
import { generateId } from '../utils/uuid';
import { logger } from '../utils/logger';

interface RecipeInput {
  name: string;
  category: string;
  cover_emoji: string;
  description: string;
  tags: string[];
  difficulty: 'easy' | 'medium' | 'hard';
  cook_time: number;
  servings: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  ingredients: string[];
  steps: string[];
}

const japaneseRecipes: RecipeInput[] = [
  {
    name: '味噌拉面',
    category: '日式拉面',
    cover_emoji: '🍜',
    description: '浓郁味噌汤底搭配弹牙拉面，温暖人心的经典日式拉面',
    tags: ['日料', '拉面', '暖胃', '主食'],
    difficulty: 'medium',
    cook_time: 45,
    servings: 2,
    calories: 520,
    protein: 28,
    carbs: 58,
    fat: 18,
    ingredients: ['拉面 200g', '味噌 3汤匙', '鸡汤 800ml', '五花肉 150g', '溏心蛋 2个', '玉米粒 50g', '黄油 15g', '葱花 适量', '海苔 2片'],
    steps: ['五花肉用酱油和味醂腌制后慢煮至软烂切片', '鸡汤加热加入味噌搅拌溶解', '拉面煮至弹牙捞出放入碗中', '倒入味噌汤底', '摆上叉烧肉、溏心蛋、玉米粒和海苔', '撒上葱花和一小块黄油即可'],
  },
  {
    name: '日式咖喱饭',
    category: '日式料理',
    cover_emoji: '🍛',
    description: '浓稠香甜的日式咖喱搭配米饭，是最受欢迎的家常料理之一',
    tags: ['日料', '咖喱', '主食', '家常菜'],
    difficulty: 'easy',
    cook_time: 40,
    servings: 3,
    calories: 650,
    protein: 30,
    carbs: 72,
    fat: 24,
    ingredients: ['鸡腿肉 300g', '洋葱 1个', '胡萝卜 1根', '土豆 2个', '咖喱块 100g', '米饭 600g', '黄油 20g', '生抽 1汤匙', '水 500ml'],
    steps: ['鸡腿肉切块，洋葱切块，胡萝卜和土豆滚刀切', '黄油融化后炒香洋葱至透明', '加入鸡肉煎至表面金黄', '加入胡萝卜和土豆翻炒', '加水煮开后转小火炖15分钟', '关火加入咖喱块搅拌至融化', '再小火煮5分钟至浓稠，搭配米饭食用'],
  },
  {
    name: '天妇罗拼盘',
    category: '日式料理',
    cover_emoji: '🍤',
    description: '酥脆轻盈的天妇罗面衣包裹鲜嫩食材，蘸天汁食用风味绝佳',
    tags: ['日料', '炸物', '海鲜', '蔬菜'],
    difficulty: 'hard',
    cook_time: 30,
    servings: 2,
    calories: 380,
    protein: 22,
    carbs: 28,
    fat: 20,
    ingredients: ['大虾 6只', '红薯 1个', '茄子 1个', '青椒 2个', '低筋面粉 100g', '冰水 150ml', '鸡蛋 1个', '天汁 适量', '萝卜泥 适量'],
    steps: ['大虾去壳留尾，背部开刀去虾线', '蔬菜切成薄片', '冰水加蛋液搅匀，筛入低筋面粉轻轻搅拌（保留颗粒感）', '将食材裹上薄薄一层面衣', '油温170度，先炸蔬菜再炸虾', '炸至金黄捞出沥油', '搭配天汁和萝卜泥食用'],
  },
  {
    name: '章鱼小丸子',
    category: '日式小食',
    cover_emoji: '🐙',
    description: '外酥里嫩的经典日式街头小吃，满满的章鱼块和浓郁酱汁',
    tags: ['日料', '小食', '街头美食', '章鱼'],
    difficulty: 'hard',
    cook_time: 25,
    servings: 2,
    calories: 280,
    protein: 15,
    carbs: 32,
    fat: 12,
    ingredients: ['章鱼 150g', '低筋面粉 150g', '鸡蛋 2个', '水 300ml', '泡打粉 1茶匙', '卷心菜 100g', '葱花 适量', '红姜 适量', '大阪烧酱 适量', '蛋黄酱 适量', '木鱼花 适量', '海苔粉 适量'],
    steps: ['章鱼切小块焯水备用', '面粉、鸡蛋、水和泡打粉调成面糊', '卷心菜切碎', '专用丸子锅烧热刷油', '倒入面糊七分满', '放入章鱼块、卷心菜和红姜', '待底部凝固后翻转成球形', '反复翻烤至金黄', '刷上酱汁和蛋黄酱，撒木鱼花和海苔粉'],
  },
  {
    name: '日式照烧鸡腿',
    category: '日式料理',
    cover_emoji: '🍗',
    description: '照烧酱汁浓郁香甜，鸡腿肉外焦里嫩，搭配米饭绝佳',
    tags: ['日料', '照烧', '鸡肉', '主食'],
    difficulty: 'easy',
    cook_time: 25,
    servings: 2,
    calories: 420,
    protein: 35,
    carbs: 24,
    fat: 22,
    ingredients: ['鸡腿 2只', '酱油 3汤匙', '味醂 2汤匙', '清酒 1汤匙', '白糖 1汤匙', '蜂蜜 1茶匙', '姜片 3片', '白芝麻 适量', '西兰花 适量'],
    steps: ['鸡腿去骨，用厨房纸吸干水分', '平底锅不放油，鸡皮朝下煎至金黄', '翻面继续煎至两面金黄', '倒出多余油脂', '混合酱油、味醂、清酒、糖和蜂蜜调成照烧汁', '倒入照烧汁小火收浓', '不断翻面使酱汁均匀裹上', '切片后淋上锅内余汁，撒白芝麻'],
  },
  {
    name: '三文鱼刺身',
    category: '日式料理',
    cover_emoji: '🍣',
    description: '新鲜肥美的三文鱼刺身，入口即化的极致鲜美',
    tags: ['日料', '刺身', '三文鱼', '生食'],
    difficulty: 'easy',
    cook_time: 10,
    servings: 2,
    calories: 250,
    protein: 28,
    carbs: 6,
    fat: 14,
    ingredients: ['三文鱼刺身级 300g', '寿司酱油 适量', '山葵 适量', '白萝卜丝 适量', '大叶紫苏 4片', '柠檬 半个', '冰水 适量'],
    steps: ['三文鱼放入冰箱冷冻室稍冻硬（方便切）', '刀沾水，将三文鱼切成0.5cm厚的薄片', '盘中摆上大叶紫苏', '将刺身片整齐排列', '搭配白萝卜丝和柠檬片', '蘸寿司酱油和山葵食用'],
  },
  {
    name: '牛丼',
    category: '日式料理',
    cover_emoji: '🥩',
    description: '肥牛搭配洋葱在甘甜酱油汁中烹煮，盖在热米饭上的一碗满足',
    tags: ['日料', '牛肉', '盖饭', '快手'],
    difficulty: 'easy',
    cook_time: 15,
    servings: 2,
    calories: 580,
    protein: 32,
    carbs: 52,
    fat: 26,
    ingredients: ['肥牛片 300g', '洋葱 1个', '酱油 3汤匙', '味醂 2汤匙', '清酒 1汤匙', '白糖 1汤匙', '高汤 150ml', '米饭 400g', '红姜 适量', '葱花 适量'],
    steps: ['洋葱切薄丝', '高汤、酱油、味醂、清酒和糖混合煮开', '放入洋葱丝煮至变软', '放入肥牛片打散', '煮至牛肉变色入味', '碗中盛热米饭', '铺上牛肉和洋葱', '淋上汤汁，佐红姜和葱花'],
  },
  {
    name: '日式蛋包饭',
    category: '日式料理',
    cover_emoji: '🍳',
    description: '滑嫩蛋皮包裹番茄炒饭，淋上番茄酱的经典日式洋食',
    tags: ['日料', '蛋包饭', '洋食', '主食'],
    difficulty: 'medium',
    cook_time: 25,
    servings: 2,
    calories: 450,
    protein: 20,
    carbs: 48,
    fat: 18,
    ingredients: ['米饭 400g', '鸡蛋 4个', '鸡胸肉 150g', '洋葱 半个', '番茄 1个', '番茄酱 3汤匙', '黄油 20g', '牛奶 2汤匙', '盐 适量', '胡椒粉 适量'],
    steps: ['鸡胸肉切小丁，洋葱和番茄切碎', '黄油炒香洋葱，加入鸡肉炒熟', '加入番茄和番茄酱翻炒', '倒入米饭炒匀，盐和胡椒调味', '鸡蛋加牛奶和盐打散', '平底锅融化黄油，倒入蛋液摊成蛋皮', '蛋皮半熟时放入炒饭', '将蛋皮对折包住炒饭，滑入盘中', '挤上番茄酱装饰'],
  },
  {
    name: '日式炒面',
    category: '日式料理',
    cover_emoji: '🥢',
    description: '酱香浓郁的日式炒面，搭配蔬菜和肉片，简单快捷的美味',
    tags: ['日料', '炒面', '主食', '快手'],
    difficulty: 'easy',
    cook_time: 15,
    servings: 2,
    calories: 480,
    protein: 22,
    carbs: 55,
    fat: 18,
    ingredients: ['日式炒面 300g', '猪五花肉 100g', '卷心菜 200g', '胡萝卜 半根', '豆芽 100g', '日式炒面酱 4汤匙', '蛋黄酱 适量', '木鱼花 适量', '海苔粉 适量'],
    steps: ['五花肉切片，卷心菜切块，胡萝卜切丝', '面条在微波炉加热1分钟', '平底锅炒香五花肉出油', '加入蔬菜翻炒', '加入面条翻炒均匀', '倒入炒面酱大火翻炒', '装盘后挤上蛋黄酱', '撒木鱼花和海苔粉'],
  },
  {
    name: '酱油拉面',
    category: '日式拉面',
    cover_emoji: '🍜',
    description: '清澈鲜美的酱油汤底，传统东京风味的经典拉面',
    tags: ['日料', '拉面', '酱油', '主食'],
    difficulty: 'medium',
    cook_time: 50,
    servings: 2,
    calories: 500,
    protein: 26,
    carbs: 55,
    fat: 20,
    ingredients: ['拉面 200g', '鸡骨 300g', '酱油 4汤匙', '味醂 1汤匙', '清酒 1汤匙', '葱花 适量', '叉烧肉 6片', '溏心蛋 2个', '海苔 2片', '笋干 30g'],
    steps: ['鸡骨焯水后加水熬煮30分钟制成汤底', '酱油、味醂和清酒混合成调味汁', '汤底过滤后加入调味汁', '面条煮至弹牙', '碗中倒入汤底放入面条', '摆上叉烧肉、溏心蛋、笋干和海苔', '撒上葱花即可'],
  },
  {
    name: '寿司拼盘',
    category: '日式料理',
    cover_emoji: '🍣',
    description: '精选多种新鲜鱼生制作的手握寿司，色彩缤纷味道丰富',
    tags: ['日料', '寿司', '海鲜', '宴客'],
    difficulty: 'hard',
    cook_time: 60,
    servings: 4,
    calories: 350,
    protein: 24,
    carbs: 38,
    fat: 12,
    ingredients: ['寿司米 300g', '寿司醋 50ml', '三文鱼 100g', '金枪鱼 100g', '虾 6只', '鳗鱼 100g', '牛油果 1个', '海苔 适量', '山葵 适量', '寿司酱油 适量', '姜片 适量'],
    steps: ['寿司米洗净煮熟，趁热拌入寿司醋放凉', '三文鱼和金枪鱼切成薄片', '虾煮熟去壳对半剖开', '鳗鱼切条、牛油果切片', '手蘸醋水，取适量饭团握成椭圆形', '在饭团上放鱼生或 toppings 捏紧', '摆盘后搭配山葵、寿司酱油和姜片食用'],
  },
  {
    name: '日式炸猪排',
    category: '日式料理',
    cover_emoji: '🥩',
    description: '外酥里嫩的金黄炸猪排，搭配特制酱汁和卷心菜丝的经典日料',
    tags: ['日料', '炸猪排', '炸物', '主食'],
    difficulty: 'medium',
    cook_time: 25,
    servings: 2,
    calories: 550,
    protein: 35,
    carbs: 32,
    fat: 28,
    ingredients: ['猪里脊肉 300g', '面包糠 100g', '低筋面粉 50g', '鸡蛋 2个', '卷心菜 200g', '猪排酱 适量', '盐 适量', '胡椒粉 适量', '食用油 适量'],
    steps: ['猪里脊肉用刀背拍松，边缘切几刀防止卷曲', '撒盐和胡椒调味', '依次裹上薄面粉、蛋液和面包糠', '油温170度炸4分钟', '翻面再炸3分钟至金黄', '捞出沥油切条', '卷心菜切细丝垫盘底', '摆上猪排淋猪排酱'],
  },
  {
    name: '味噌汤',
    category: '日式汤品',
    cover_emoji: '🥣',
    description: '简单暖心的日式味噌汤，豆腐海带芽的组合清淡鲜美',
    tags: ['日料', '汤品', '豆腐', '快手'],
    difficulty: 'easy',
    cook_time: 10,
    servings: 2,
    calories: 120,
    protein: 8,
    carbs: 10,
    fat: 5,
    ingredients: ['味噌 2汤匙', '嫩豆腐 200g', '海带芽 适量', '葱花 适量', '高汤 600ml', '水 适量'],
    steps: ['高汤烧开', '豆腐切小丁放入汤中', '海带芽泡发后放入', '关火后把味噌放在汤勺中化开入锅', '撒葱花即可出锅'],
  },
  {
    name: '日式煎饺',
    category: '日式小食',
    cover_emoji: '🥟',
    description: '底部酥脆的日式煎饺，多汁的猪肉馅搭配焦香外皮',
    tags: ['日料', '饺子', '煎饺', '小食'],
    difficulty: 'medium',
    cook_time: 25,
    servings: 3,
    calories: 320,
    protein: 18,
    carbs: 28,
    fat: 16,
    ingredients: ['饺子皮 30张', '猪肉末 250g', '卷心菜 200g', '韭菜 50g', '姜末 1茶匙', '酱油 1汤匙', '香油 1茶匙', '食用油 适量', '水 适量'],
    steps: ['卷心菜切碎加盐腌制后挤干水分', '猪肉末加入姜末、酱油、香油搅拌上劲', '加入卷心菜和韭菜碎拌匀成馅', '包成饺子', '平底锅倒油摆放饺子', '中火煎至底部金黄', '倒入水至饺子三分之一高度', '盖盖蒸至水分收干，底部再次煎脆'],
  },
  {
    name: '亲子丼',
    category: '日式料理',
    cover_emoji: '🍚',
    description: '鸡肉和鸡蛋的完美组合，"亲子"同锅的温暖盖饭',
    tags: ['日料', '鸡肉', '鸡蛋', '盖饭'],
    difficulty: 'easy',
    cook_time: 15,
    servings: 2,
    calories: 540,
    protein: 34,
    carbs: 48,
    fat: 22,
    ingredients: ['鸡腿肉 250g', '鸡蛋 4个', '洋葱 1个', '高汤 200ml', '酱油 2汤匙', '味醂 2汤匙', '清酒 1汤匙', '白糖 1茶匙', '米饭 400g', '三叶芹 适量'],
    steps: ['鸡腿肉切一口大小，洋葱切丝', '高汤、酱油、味醂、清酒和糖混合煮开', '放入洋葱丝煮软', '平铺鸡肉煮熟', '鸡蛋打散但不要打太匀', '转圈倒入一半蛋液，盖盖煮半分钟', '倒入剩余蛋液煮至半熟关火', '盛在米饭上，点缀三叶芹'],
  },
  {
    name: '日式乌冬面',
    category: '日式料理',
    cover_emoji: '🍜',
    description: 'Q弹爽滑的乌冬面搭配清澈的日式高汤，简单纯粹的美味',
    tags: ['日料', '乌冬', '面食', '清淡'],
    difficulty: 'easy',
    cook_time: 15,
    servings: 2,
    calories: 380,
    protein: 14,
    carbs: 52,
    fat: 10,
    ingredients: ['冷冻乌冬面 2份', '高汤 600ml', '酱油 2汤匙', '味醂 1汤匙', '葱花 适量', '天妇罗花 适量', '鱼板 4片', '海苔 适量'],
    steps: ['高汤加入酱油和味醂煮开', '乌冬面煮至Q弹捞出', '放入碗中倒入热汤', '摆上鱼板和葱花', '撒上天妇罗花和海苔碎'],
  },
  {
    name: '日式饭团',
    category: '日式小食',
    cover_emoji: '🍙',
    description: '三角饭团是经典的日式便当主食，简单便携又美味',
    tags: ['日料', '饭团', '便当', '小食'],
    difficulty: 'easy',
    cook_time: 20,
    servings: 4,
    calories: 200,
    protein: 8,
    carbs: 34,
    fat: 4,
    ingredients: ['米饭 500g', '三文鱼肉松 50g', '梅干 4颗', '海苔 4片', '盐 适量', '白芝麻 适量'],
    steps: ['米饭趁热撒盐拌匀', '手蘸盐水防粘', '取适量米饭压平', '中间放入三文鱼肉松或梅干', '捏成三角形状', '底部贴上海苔片', '撒白芝麻即可'],
  },
  {
    name: '日式豆腐沙拉',
    category: '日式沙拉',
    cover_emoji: '🥗',
    description: '清爽的嫩豆腐沙拉搭配和风芝麻酱，健康低脂的开胃前菜',
    tags: ['日料', '沙拉', '豆腐', '低卡'],
    difficulty: 'easy',
    cook_time: 10,
    servings: 2,
    calories: 180,
    protein: 14,
    carbs: 10,
    fat: 10,
    ingredients: ['嫩豆腐 300g', '芝麻酱 2汤匙', '酱油 1汤匙', '醋 1汤匙', '糖 半茶匙', '香油 1茶匙', '生菜 适量', '小番茄 6个', '白芝麻 适量'],
    steps: ['豆腐用厨房纸包裹沥干水分', '芝麻酱、酱油、醋、糖和香油调成酱汁', '生菜铺底', '豆腐切片摆上', '淋上酱汁', '撒白芝麻，搭配小番茄'],
  },
  {
    name: '日式关东煮',
    category: '日式汤品',
    cover_emoji: '🥘',
    description: '清淡鲜美的关东煮，各种食材在高汤中慢煮吸满汤汁',
    tags: ['日料', '关东煮', '汤品', '暖胃'],
    difficulty: 'easy',
    cook_time: 40,
    servings: 3,
    calories: 250,
    protein: 16,
    carbs: 22,
    fat: 10,
    ingredients: ['白萝卜 半根', '鸡蛋 3个', '鱼丸 100g', '竹轮 100g', '油豆腐 100g', '蒟蒻 100g', '昆布 1片', '酱油 3汤匙', '味醂 2汤匙', '清酒 1汤匙', '水 1000ml'],
    steps: ['白萝卜切厚片焯水去苦味', '鸡蛋煮熟剥壳', '昆布加水煮10分钟后取出', '加入酱油、味醂和清酒调成汤底', '放入白萝卜和鸡蛋煮20分钟', '加入其他食材继续煮10分钟', '盛入碗中搭配黄芥末食用'],
  },
  {
    name: '鳗鱼饭',
    category: '日式料理',
    cover_emoji: '🍱',
    description: '蒲烧鳗鱼搭配热米饭，甜咸适口的鳗鱼酱汁让人欲罢不能',
    tags: ['日料', '鳗鱼', '盖饭', '经典'],
    difficulty: 'medium',
    cook_time: 30,
    servings: 2,
    calories: 620,
    protein: 32,
    carbs: 52,
    fat: 28,
    ingredients: ['蒲烧鳗鱼 2条', '米饭 400g', '酱油 2汤匙', '味醂 2汤匙', '清酒 1汤匙', '白糖 1汤匙', '山椒粉 适量', '海苔丝 适量'],
    steps: ['酱油、味醂、清酒和糖调成蒲烧汁', '鳗鱼在烤架上两面各烤2分钟', '刷上蒲烧汁继续烤至表面焦亮', '反复刷烤2-3次', '米饭盛入碗中', '烤好的鳗鱼切段铺在饭上', '淋剩余蒲烧汁，撒山椒粉和海苔丝'],
  },
];

const koreanRecipes: RecipeInput[] = [
  {
    name: '韩式拌饭',
    category: '韩式料理',
    cover_emoji: '🍚',
    description: '色彩缤纷的韩式拌饭，多种蔬菜搭配辣酱和溏心蛋搅拌均匀',
    tags: ['韩料', '拌饭', '主食', '蔬菜'],
    difficulty: 'medium',
    cook_time: 35,
    servings: 2,
    calories: 520,
    protein: 22,
    carbs: 58,
    fat: 20,
    ingredients: ['米饭 400g', '牛肉末 150g', '菠菜 100g', '胡萝卜 1根', '豆芽 100g', '香菇 5朵', '鸡蛋 2个', '韩式辣酱 3汤匙', '香油 2汤匙', '酱油 1汤匙', '芝麻 适量', '海苔碎 适量'],
    steps: ['各种蔬菜分别焯水或炒熟，加盐和香油调味', '牛肉末用酱油和糖炒熟', '煎一个溏心蛋', '碗底刷香油放入米饭', '将各种蔬菜和牛肉分别码在饭上', '中间放溏心蛋', '挤上韩式辣酱', '撒芝麻和海苔碎，拌匀食用'],
  },
  {
    name: '韩式烤肉',
    category: '韩式料理',
    cover_emoji: '🥩',
    description: '滋滋作响的韩式烤五花肉，包上生菜蘸酱吃最地道',
    tags: ['韩料', '烤肉', '五花肉', '聚餐'],
    difficulty: 'medium',
    cook_time: 30,
    servings: 3,
    calories: 580,
    protein: 30,
    carbs: 18,
    fat: 42,
    ingredients: ['五花肉 500g', '生菜 1棵', '紫苏叶 适量', '大蒜 5瓣', '青辣椒 3个', '韩式辣酱 3汤匙', '包饭酱 3汤匙', '泡菜 适量', '盐 适量', '芝麻油 适量'],
    steps: ['五花肉切厚片（约0.5cm）', '平底锅或烤盘加热不用放油', '放入五花肉片煎至两面金黄', '用剪刀剪成小块', '大蒜切片，青椒切圈', '生菜和紫苏叶洗净沥干', '取一片生菜放上烤肉、蒜片、青椒和泡菜', '蘸酱后包起食用'],
  },
  {
    name: '韩式炸鸡',
    category: '韩式料理',
    cover_emoji: '🍗',
    description: '外酥里嫩的韩式炸鸡，裹上甜辣酱汁，让人停不下来',
    tags: ['韩料', '炸鸡', '小食', '宵夜'],
    difficulty: 'medium',
    cook_time: 40,
    servings: 3,
    calories: 450,
    protein: 28,
    carbs: 22,
    fat: 26,
    ingredients: ['鸡翅中 500g', '鸡腿 500g', '低筋面粉 100g', '玉米淀粉 50g', '鸡蛋 1个', '牛奶 100ml', '韩式辣酱 3汤匙', '番茄酱 3汤匙', '蜂蜜 2汤匙', '蒜末 1汤匙', '食用油 适量', '白芝麻 适量'],
    steps: ['鸡肉用牛奶和盐腌制30分钟', '面粉、淀粉和鸡蛋调成面糊', '鸡肉裹上面糊', '油温160度炸8分钟捞出', '升温至180度复炸2分钟至酥脆', '韩式辣酱、番茄酱、蜂蜜和蒜末调成酱汁', '酱汁加热后放入炸鸡翻炒裹匀', '撒白芝麻即可'],
  },
  {
    name: '泡菜豆腐汤',
    category: '韩式汤品',
    cover_emoji: '🥘',
    description: '酸辣开胃的泡菜豆腐汤，热腾腾的一锅暖胃又满足',
    tags: ['韩料', '汤品', '泡菜', '豆腐'],
    difficulty: 'easy',
    cook_time: 20,
    servings: 2,
    calories: 220,
    protein: 16,
    carbs: 12,
    fat: 14,
    ingredients: ['韩国泡菜 200g', '嫩豆腐 300g', '五花肉 100g', '洋葱 半个', '大葱 1根', '韩式辣酱 1汤匙', '辣椒粉 1茶匙', '蒜末 1茶匙', '淘米水 500ml', '食用油 适量', '香油 1茶匙'],
    steps: ['五花肉切薄片，豆腐切块，洋葱切丝', '锅中倒油炒香五花肉', '加入泡菜翻炒出香味', '加入洋葱、蒜末和辣椒粉翻炒', '倒入淘米水和韩式辣酱煮开', '放入豆腐煮5分钟入味', '撒葱花和香油即可'],
  },
  {
    name: '韩式炒年糕',
    category: '韩式料理',
    cover_emoji: '🍥',
    description: 'Q弹软糯的韩式炒年糕，甜辣酱汁浓郁入味',
    tags: ['韩料', '年糕', '小食', '辣味'],
    difficulty: 'easy',
    cook_time: 15,
    servings: 2,
    calories: 380,
    protein: 10,
    carbs: 62,
    fat: 8,
    ingredients: ['韩式年糕 300g', '鱼饼 100g', '韩式辣酱 3汤匙', '辣椒粉 1茶匙', '糖 1汤匙', '酱油 1汤匙', '蒜末 1茶匙', '大葱 1根', '水 300ml', '熟芝麻 适量'],
    steps: ['年糕用清水浸泡10分钟', '鱼饼切三角形', '锅中倒入水加入辣酱、辣椒粉、糖和酱油煮开', '放入年糕煮软', '加入鱼饼同煮', '大火收汁至浓稠', '撒葱花和芝麻即可'],
  },
  {
    name: '韩式冷面',
    category: '韩式料理',
    cover_emoji: '🍜',
    description: '冰爽酸甜的韩式冷面，炎炎夏日的一抹清凉',
    tags: ['韩料', '冷面', '面食', '夏日'],
    difficulty: 'medium',
    cook_time: 20,
    servings: 2,
    calories: 350,
    protein: 16,
    carbs: 50,
    fat: 8,
    ingredients: ['冷面 300g', '牛肉 150g', '黄瓜 半根', '梨 半个', '鸡蛋 2个', '泡菜 适量', '醋 3汤匙', '白糖 2汤匙', '酱油 2汤匙', '冰块 适量', '白芝麻 适量'],
    steps: ['牛肉加水煮成清汤，冷却后撇去油脂', '汤中加入醋、糖和酱油调成冷面汤，冷藏', '冷面煮至弹牙捞出用冰水搓洗', '黄瓜和梨切丝', '鸡蛋煮熟对半切', '碗中放入冷面倒入冰汤', '摆上牛肉、黄瓜丝、梨丝、鸡蛋和泡菜', '撒白芝麻和冰块即可'],
  },
  {
    name: '海鲜葱饼',
    category: '韩式小食',
    cover_emoji: '🥞',
    description: '外脆内软的海鲜葱饼，满满的葱花和海鲜搭配蘸料',
    tags: ['韩料', '煎饼', '海鲜', '小食'],
    difficulty: 'easy',
    cook_time: 15,
    servings: 2,
    calories: 280,
    protein: 16,
    carbs: 28,
    fat: 12,
    ingredients: ['低筋面粉 150g', '水 200ml', '鸡蛋 1个', '大葱 3根', '虾仁 100g', '鱿鱼 100g', '青辣椒 2个', '食用油 适量', '蘸料（酱油+醋+辣椒粉）适量'],
    steps: ['面粉、水和鸡蛋调成面糊', '大葱切段，虾仁和鱿鱼切小块', '青椒切圈', '平底锅倒油烧热', '倒入面糊铺平', '摆上葱段、海鲜和青椒圈', '煎至底部金黄后翻面', '两面煎脆出锅搭配蘸料'],
  },
  {
    name: '韩式部队锅',
    category: '韩式汤品',
    cover_emoji: '🥘',
    description: '丰盛的韩式部队锅，各种食材在辣汤中沸腾，暖心又过瘾',
    tags: ['韩料', '部队锅', '火锅', '聚餐'],
    difficulty: 'easy',
    cook_time: 25,
    servings: 3,
    calories: 480,
    protein: 26,
    carbs: 34,
    fat: 24,
    ingredients: ['午餐肉 200g', '香肠 100g', '泡菜 200g', '年糕 150g', '拉面 1包', '嫩豆腐 200g', '金针菇 100g', '洋葱 半个', '大葱 1根', '韩式辣酱 2汤匙', '辣椒粉 1汤匙', '酱油 1汤匙', '糖 1茶匙', '芝士片 2片', '水 500ml'],
    steps: ['午餐肉和香肠切片，豆腐切块，洋葱切丝', '锅中铺上泡菜和洋葱', '依次摆放午餐肉、香肠、豆腐、年糕和金针菇', '韩式辣酱、辣椒粉、酱油和糖加水调匀', '倒入锅中煮开', '煮至食材熟透后放入拉面和芝士片', '撒葱花即可'],
  },
  {
    name: '韩式紫菜包饭',
    category: '韩式小食',
    cover_emoji: '🍙',
    description: '韩式紫菜包饭，色彩缤纷的馅料卷在香糯的米饭中',
    tags: ['韩料', '紫菜包饭', '便当', '小食'],
    difficulty: 'medium',
    cook_time: 25,
    servings: 3,
    calories: 320,
    protein: 14,
    carbs: 42,
    fat: 10,
    ingredients: ['海苔 5张', '米饭 500g', '胡萝卜 1根', '菠菜 100g', '鸡蛋 3个', '火腿 100g', '腌萝卜 适量', '香油 1汤匙', '芝麻 1汤匙', '盐 适量'],
    steps: ['米饭趁热加香油、芝麻和盐拌匀', '鸡蛋摊成蛋皮切丝', '胡萝卜切丝炒熟，菠菜焯水', '火腿和腌萝卜切条', '竹帘上铺海苔', '均匀铺上米饭（留1cm边缘）', '中间依次放上各种馅料', '卷紧后切段装盘'],
  },
  {
    name: '韩式辣炒猪肉',
    category: '韩式料理',
    cover_emoji: '🥩',
    description: '辣味十足的韩式炒猪肉，搭配蔬菜大火快炒的经典家常菜',
    tags: ['韩料', '猪肉', '辣炒', '家常菜'],
    difficulty: 'easy',
    cook_time: 20,
    servings: 2,
    calories: 460,
    protein: 28,
    carbs: 16,
    fat: 30,
    ingredients: ['猪五花肉 300g', '洋葱 1个', '大葱 1根', '青辣椒 3个', '韩式辣酱 2汤匙', '辣椒粉 1汤匙', '酱油 1汤匙', '糖 1汤匙', '蒜末 1汤匙', '生姜末 1茶匙', '香油 1茶匙', '白芝麻 适量'],
    steps: ['五花肉切薄片，洋葱切丝，大葱斜切', '辣酱、辣椒粉、酱油、糖、蒜末和姜末调成腌料', '肉片用腌料抓匀腌制10分钟', '大火热锅不放油直接炒肉片', '炒至变色出油后加入洋葱', '加入大葱和青椒快速翻炒', '淋香油撒芝麻即可'],
  },
  {
    name: '参鸡汤',
    category: '韩式汤品',
    cover_emoji: '🥣',
    description: '滋补养生的韩式参鸡汤，鲜嫩的鸡肉中塞满糯米和药材',
    tags: ['韩料', '汤品', '鸡肉', '滋补'],
    difficulty: 'hard',
    cook_time: 90,
    servings: 2,
    calories: 420,
    protein: 36,
    carbs: 24,
    fat: 18,
    ingredients: ['童子鸡 1只', '糯米 100g', '高丽参 1根', '红枣 6颗', '大蒜 5瓣', '栗子 4颗', '大葱 1根', '盐 适量', '胡椒粉 适量', '糯米酒 适量'],
    steps: ['糯米提前浸泡2小时', '鸡洗净去内脏和尾部', '将糯米、人参、红枣、蒜和栗子塞入鸡腹中', '用牙签封口', '锅中加水没过鸡身', '大火煮开后转小火炖1小时', '加盐和胡椒调味', '搭配葱丝和糯米酒食用'],
  },
  {
    name: '韩式大酱汤',
    category: '韩式汤品',
    cover_emoji: '🥘',
    description: '醇厚的韩式大酱汤，是大酱发酵的浓郁风味搭配蔬菜豆腐',
    tags: ['韩料', '汤品', '大酱', '豆腐'],
    difficulty: 'easy',
    cook_time: 20,
    servings: 2,
    calories: 180,
    protein: 12,
    carbs: 14,
    fat: 8,
    ingredients: ['韩式大酱 2汤匙', '嫩豆腐 200g', '西葫芦 半根', '土豆 1个', '洋葱 半个', '青辣椒 2个', '大葱 1根', '蒜末 1茶匙', '淘米水 600ml', '食用油 适量'],
    steps: ['土豆和西葫芦切片，洋葱切丝', '锅中倒油炒香洋葱', '倒入淘米水烧开', '大酱用滤网在汤中化开', '放入土豆煮5分钟', '加入西葫芦和豆腐煮3分钟', '放入青椒、大葱和蒜末', '煮1分钟即可出锅'],
  },
  {
    name: '韩式杂菜拌粉丝',
    category: '韩式料理',
    cover_emoji: '🥗',
    description: 'Q弹的韩式红薯粉丝搭配多种蔬菜和牛肉，宴客必备的韩式小菜',
    tags: ['韩料', '粉丝', '拌菜', '宴客'],
    difficulty: 'medium',
    cook_time: 25,
    servings: 3,
    calories: 320,
    protein: 14,
    carbs: 38,
    fat: 14,
    ingredients: ['韩式红薯粉丝 200g', '牛肉 100g', '菠菜 100g', '胡萝卜 1根', '洋葱 半个', '香菇 5朵', '酱油 3汤匙', '香油 2汤匙', '糖 1汤匙', '芝麻 适量', '食用油 适量'],
    steps: ['粉丝用温水泡软后煮熟过凉水', '牛肉切丝用酱油和糖腌制后炒熟', '各种蔬菜分别切丝炒熟', '酱油、香油、糖和芝麻调成拌汁', '粉丝剪短放入大碗', '加入所有炒好的食材', '倒入拌汁用手抓匀', '撒芝麻装盘'],
  },
  {
    name: '泡菜炒饭',
    category: '韩式料理',
    cover_emoji: '🍚',
    description: '韩式泡菜炒饭，酸辣开胃的经典韩式快手料理',
    tags: ['韩料', '炒饭', '泡菜', '快手'],
    difficulty: 'easy',
    cook_time: 10,
    servings: 2,
    calories: 450,
    protein: 18,
    carbs: 52,
    fat: 18,
    ingredients: ['米饭 400g', '韩国泡菜 200g', '五花肉 100g', '鸡蛋 2个', '大葱 1根', '韩式辣酱 1汤匙', '酱油 1茶匙', '香油 1茶匙', '紫菜碎 适量', '白芝麻 适量', '食用油 适量'],
    steps: ['五花肉切小丁，泡菜切碎，大葱切葱花', '锅中倒油炒香五花肉', '加入泡菜翻炒出香', '加入辣酱和米饭翻炒均匀', '加酱油调味', '盛入碗中', '煎一个太阳蛋放在炒饭上', '撒紫菜碎、芝麻和葱花，淋香油'],
  },
  {
    name: '韩式鸡蛋羹',
    category: '韩式小食',
    cover_emoji: '🥚',
    description: '嫩滑如布丁的韩式石锅鸡蛋羹，入口即化的温暖小菜',
    tags: ['韩料', '鸡蛋', '小菜', '快手'],
    difficulty: 'easy',
    cook_time: 10,
    servings: 2,
    calories: 150,
    protein: 12,
    carbs: 4,
    fat: 10,
    ingredients: ['鸡蛋 4个', '水 150ml', '葱花 适量', '盐 适量', '芝麻油 1茶匙', '白芝麻 适量', '胡萝卜碎 适量'],
    steps: ['鸡蛋打散加入水和盐搅匀', '过滤蛋液去除气泡', '石锅或碗中刷芝麻油', '倒入蛋液', '盖上盖子中小火蒸8分钟', '表面凝固后撒胡萝卜碎和葱花', '淋芝麻油撒白芝麻即可'],
  },
  {
    name: '韩式辣炖排骨',
    category: '韩式料理',
    cover_emoji: '🥩',
    description: '辣中带甜的韩式炖排骨，肉质酥烂脱骨，酱汁浓郁下饭',
    tags: ['韩料', '排骨', '炖菜', '辣味'],
    difficulty: 'medium',
    cook_time: 60,
    servings: 3,
    calories: 550,
    protein: 32,
    carbs: 22,
    fat: 34,
    ingredients: ['猪排骨 600g', '土豆 2个', '胡萝卜 1根', '洋葱 1个', '韩式辣酱 3汤匙', '辣椒粉 1汤匙', '酱油 3汤匙', '糖 2汤匙', '蒜末 1汤匙', '姜末 1茶匙', '清酒 1汤匙', '香油 1茶匙', '芝麻 适量'],
    steps: ['排骨冷水下锅焯水去血沫', '辣酱、辣椒粉、酱油、糖、蒜末、姜末和清酒调成酱汁', '排骨用酱汁腌制20分钟', '锅中加少量水放入排骨和酱汁', '大火煮开后转小火炖30分钟', '加入土豆和胡萝卜继续炖15分钟', '大火收汁至浓稠', '淋香油撒芝麻即可'],
  },
  {
    name: '韩式南瓜粥',
    category: '韩式汤品',
    cover_emoji: '🥣',
    description: '细腻香甜的韩式南瓜粥，温润养胃的健康粥品',
    tags: ['韩料', '粥品', '南瓜', '养生'],
    difficulty: 'easy',
    cook_time: 25,
    servings: 2,
    calories: 200,
    protein: 6,
    carbs: 38,
    fat: 4,
    ingredients: ['南瓜 500g', '糯米粉 50g', '白糖 2汤匙', '盐 少许', '水 400ml', '枸杞 适量', '松子 适量'],
    steps: ['南瓜去皮去籽切块蒸熟', '将南瓜压成泥或用搅拌机打成糊', '糯米粉加水调成糊', '南瓜泥加水煮开', '慢慢倒入糯米糊搅拌', '煮至浓稠加糖和盐调味', '盛入碗中点缀枸杞和松子'],
  },
  {
    name: '韩式炸酱面',
    category: '韩式料理',
    cover_emoji: '🍜',
    description: '韩式炸酱面，春酱炒制的浓郁酱料搭配筋道面条和蔬菜',
    tags: ['韩料', '炸酱面', '面食', '韩式中华料理'],
    difficulty: 'medium',
    cook_time: 30,
    servings: 2,
    calories: 520,
    protein: 20,
    carbs: 56,
    fat: 22,
    ingredients: ['面条 300g', '猪肉末 200g', '春酱（韩式炸酱） 4汤匙', '土豆 1个', '洋葱 1个', '西葫芦 半根', '黄瓜 半根', '糖 1汤匙', '食用油 适量', '水 200ml'],
    steps: ['土豆和西葫芦切小丁，洋葱切碎', '春酱用油炒香备用', '锅中倒油炒猪肉末', '加入洋葱炒至透明', '加入土豆和西葫芦翻炒', '放入炒过的春酱和糖翻炒', '加水煮至浓稠', '黄瓜切丝，面条煮熟拌上酱料和黄瓜丝'],
  },
  {
    name: '韩式泡菜饺子',
    category: '韩式小食',
    cover_emoji: '🥟',
    description: '韩式泡菜饺子，酸辣的泡菜馅配上软糯的粉条，风味独特',
    tags: ['韩料', '饺子', '泡菜', '小食'],
    difficulty: 'medium',
    cook_time: 30,
    servings: 3,
    calories: 300,
    protein: 14,
    carbs: 34,
    fat: 12,
    ingredients: ['饺子皮 30张', '韩国泡菜 300g', '猪肉末 200g', '粉丝 50g', '豆腐 150g', '韭菜 50g', '蒜末 1茶匙', '香油 1汤匙', '盐 适量', '胡椒粉 适量'],
    steps: ['泡菜挤干水分切碎', '粉丝泡软后剪短', '豆腐压碎挤干水分', '大碗中放入肉末、泡菜、粉丝、豆腐和韭菜', '加入蒜末、香油、盐和胡椒粉拌匀成馅', '包成饺子', '蒸10分钟或煎至金黄', '搭配泡菜醋酱食用'],
  },
  {
    name: '韩式石锅拌饭',
    category: '韩式料理',
    cover_emoji: '🍚',
    description: '石锅中的韩式拌饭，锅底形成金黄锅巴，滋滋作响香气四溢',
    tags: ['韩料', '石锅拌饭', '主食', '经典'],
    difficulty: 'medium',
    cook_time: 30,
    servings: 2,
    calories: 560,
    protein: 24,
    carbs: 56,
    fat: 24,
    ingredients: ['米饭 400g', '牛肉 150g', '菠菜 100g', '胡萝卜 1根', '豆芽 100g', '香菇 5朵', '鸡蛋 2个', '韩式辣酱 3汤匙', '香油 2汤匙', '酱油 1汤匙', '芝麻 适量', '海苔碎 适量'],
    steps: ['石锅刷香油', '米饭盛入石锅压实', '牛肉切丝用酱油和糖腌制后炒熟', '各种蔬菜分别焯水或炒熟', '将蔬菜和牛肉分别码在米饭上', '中间放一个生鸡蛋', '石锅上火烧至滋滋响，底部形成锅巴', '挤上韩式辣酱撒芝麻和海苔碎', '拌匀食用'],
  },
];

export async function seedCuisines(): Promise<void> {
  const db = getDb();

  const insertRecipe = db.prepare(`
    INSERT OR IGNORE INTO recipes (id, name, category, cover_emoji, description, tags, difficulty, cook_time, servings, calories, protein, carbs, fat, ingredients, steps)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  let insertedCount = 0;

  const allRecipes = [...japaneseRecipes, ...koreanRecipes];
  for (const r of allRecipes) {
    const existing = db.prepare('SELECT id FROM recipes WHERE name = ?').get(r.name);
    if (existing) continue;

    insertRecipe.run(
      generateId(), r.name, r.category, r.cover_emoji, r.description,
      JSON.stringify(r.tags), r.difficulty, r.cook_time, r.servings,
      r.calories, r.protein, r.carbs, r.fat,
      JSON.stringify(r.ingredients), JSON.stringify(r.steps)
    );
    insertedCount++;
  }

  logger.info(`Cuisine seed complete: ${insertedCount} new recipes added (${japaneseRecipes.length} Japanese, ${koreanRecipes.length} Korean)`);
}

if (require.main === module) {
  (async () => {
    await seedCuisines();
    closeDb();
  })();
}
