import { Recipe } from '../types'

export const weeklyRecipes: Recipe[] = [
  // ===== 早餐 (Breakfast) =====
  {
    id: '1',
    name: '牛油果鸡胸肉沙拉',
    category: 'lunch',
    imageUrl: '',
    calories: 385,
    protein: 42,
    carbs: 18,
    fat: 16,
    prepTime: 15,
    ingredients: [
      '鸡胸肉 150g',
      '牛油果 1/2个',
      '混合生菜 100g',
      '小番茄 50g',
      '橄榄油 1汤匙',
      '柠檬汁 1汤匙',
      '盐和黑胡椒 适量',
    ],
    steps: [
      '鸡胸肉用盐和黑胡椒腌制10分钟',
      '平底锅加少许橄榄油，中火煎鸡胸肉每面6-8分钟至金黄熟透',
      '鸡胸肉稍微放凉后切片',
      '牛油果切块，小番茄对半切',
      '混合生菜、牛油果、小番茄，放上鸡胸肉片',
      '淋上橄榄油和柠檬汁即可',
    ],
    isPremium: false,
  },
  {
    id: '2',
    name: '三文鱼糙米能量碗',
    category: 'dinner',
    imageUrl: '',
    calories: 520,
    protein: 38,
    carbs: 45,
    fat: 18,
    prepTime: 25,
    ingredients: [
      '三文鱼 150g',
      '糙米 100g',
      '西兰花 80g',
      '胡萝卜 50g',
      '毛豆 30g',
      '酱油 1汤匙',
      '芝麻油 1茶匙',
      '白芝麻 适量',
    ],
    steps: [
      '糙米提前浸泡30分钟，煮熟备用',
      '三文鱼用少许盐和黑胡椒调味',
      '平底锅中小火煎三文鱼每面4-5分钟',
      '西兰花和胡萝卜焯水2分钟',
      '碗中放入糙米底，摆上三文鱼和蔬菜',
      '淋上酱油和芝麻油，撒白芝麻',
    ],
    isPremium: false,
  },
  {
    id: '3',
    name: '蛋白质莓果奶昔',
    category: 'breakfast',
    imageUrl: '',
    calories: 280,
    protein: 25,
    carbs: 32,
    fat: 6,
    prepTime: 5,
    ingredients: [
      '蛋白粉 1勺',
      '冷冻混合莓果 80g',
      '香蕉 1根',
      '牛奶/杏仁奶 200ml',
      '奇亚籽 1汤匙',
      '蜂蜜 1茶匙',
    ],
    steps: [
      '将所有材料放入搅拌机',
      '高速搅拌30-45秒至顺滑',
      '倒入杯中即可享用',
    ],
    isPremium: false,
  },
  {
    id: '4',
    name: '韩式牛肉拌饭',
    category: 'lunch',
    imageUrl: '',
    calories: 445,
    protein: 32,
    carbs: 50,
    fat: 14,
    prepTime: 30,
    ingredients: [
      '牛肉片 100g',
      '米饭 150g',
      '菠菜 50g',
      '豆芽 50g',
      '胡萝卜丝 30g',
      '鸡蛋 1个',
      '韩式辣酱 1汤匙',
      '芝麻油 1茶匙',
    ],
    steps: [
      '牛肉片用酱油、芝麻油、蒜末腌制15分钟',
      '菠菜焯水，拌入少许芝麻油和盐',
      '豆芽焯水沥干',
      '煎一个太阳蛋',
      '碗中放入米饭，依次摆上各种蔬菜和牛肉',
      '中间放煎蛋，配上韩式辣酱',
    ],
    isPremium: false,
  },
  {
    id: '5',
    name: '藜麦虾仁牛油果沙拉',
    category: 'lunch',
    imageUrl: '',
    calories: 420,
    protein: 35,
    carbs: 30,
    fat: 18,
    prepTime: 20,
    ingredients: [
      '虾仁 120g',
      '藜麦 60g',
      '牛油果 1/2个',
      '黄瓜 50g',
      '芒果 50g',
      '香菜 适量',
      '青柠汁 1汤匙',
    ],
    steps: [
      '藜麦冲洗后加水煮15分钟，沥干放凉',
      '虾仁用盐和黑胡椒腌制，煎至两面变红',
      '牛油果、黄瓜、芒果切丁',
      '所有材料放入大碗混合',
      '加入青柠汁和少许盐调味',
    ],
    isPremium: true,
  },
  {
    id: '6',
    name: '红薯鸡肉暖沙拉',
    category: 'dinner',
    imageUrl: '',
    calories: 460,
    protein: 40,
    carbs: 48,
    fat: 12,
    prepTime: 35,
    ingredients: [
      '鸡腿肉 150g',
      '红薯 200g',
      '羽衣甘蓝 60g',
      '石榴籽 30g',
      '核桃 20g',
      '蜂蜜芥末酱 1汤匙',
    ],
    steps: [
      '红薯切块，200度烤25分钟至金黄',
      '鸡腿肉用盐、胡椒、蒜粉腌制，煎熟切片',
      '羽衣甘蓝撕小片，用橄榄油按摩软化',
      '盘中放羽衣甘蓝底，摆上红薯、鸡肉',
      '撒石榴籽和核桃碎，淋蜂蜜芥末酱',
    ],
    isPremium: true,
  },
  {
    id: '7',
    name: '隔夜燕麦杯',
    category: 'breakfast',
    imageUrl: '',
    calories: 320,
    protein: 18,
    carbs: 45,
    fat: 10,
    prepTime: 5,
    ingredients: [
      '燕麦片 50g',
      '牛奶/植物奶 150ml',
      '希腊酸奶 2汤匙',
      '奇亚籽 1汤匙',
      '蓝莓 30g',
      '香蕉片 30g',
      '坚果碎 15g',
    ],
    steps: [
      '在密封罐中混合燕麦、牛奶、酸奶、奇亚籽',
      '摇匀后放入冰箱冷藏过夜',
      '早上取出，表面放蓝莓、香蕉片和坚果碎',
      '也可以加入一勺蛋白粉增加蛋白质',
    ],
    isPremium: false,
  },
  {
    id: '8',
    name: '味噌三文鱼配时蔬',
    category: 'dinner',
    imageUrl: '',
    calories: 490,
    protein: 42,
    carbs: 22,
    fat: 22,
    prepTime: 30,
    ingredients: [
      '三文鱼 150g',
      '白味噌 1汤匙',
      '味醂 1汤匙',
      '酱油 1茶匙',
      '芦笋 80g',
      '杏鲍菇 60g',
      '毛豆 40g',
    ],
    steps: [
      '味噌、味醂、酱油混合成酱汁',
      '三文鱼用酱汁腌制15分钟',
      '芦笋切段，杏鲍菇切片',
      '三文鱼放入200度烤箱烤12-15分钟',
      '同时平底锅炒芦笋和杏鲍菇',
      '毛豆焯水后一起摆盘',
    ],
    isPremium: true,
  },
  {
    id: '9',
    name: '鹰嘴豆蔬菜卷',
    category: 'lunch',
    imageUrl: '',
    calories: 350,
    protein: 16,
    carbs: 42,
    fat: 12,
    prepTime: 10,
    ingredients: [
      '全麦卷饼 1张',
      '鹰嘴豆泥 3汤匙',
      '烤红椒 30g',
      '生菜 30g',
      '黄瓜条 40g',
      '紫甘蓝丝 30g',
      '番茄 30g',
    ],
    steps: [
      '全麦卷饼在平底锅加热30秒',
      '抹上鹰嘴豆泥',
      '依次铺上生菜、黄瓜条、紫甘蓝丝、番茄',
      '放上烤红椒',
      '紧紧卷起，从中间斜切一刀',
    ],
    isPremium: false,
  },
  {
    id: '10',
    name: '抹茶奇亚籽布丁',
    category: 'snack',
    imageUrl: '',
    calories: 190,
    protein: 8,
    carbs: 22,
    fat: 9,
    prepTime: 5,
    ingredients: [
      '奇亚籽 3汤匙',
      '椰奶 150ml',
      '抹茶粉 1茶匙',
      '枫糖浆 1汤匙',
      '香草精 1/2茶匙',
      '椰子片 适量',
    ],
    steps: [
      '椰奶中加入抹茶粉，搅拌至完全溶解',
      '加入奇亚籽、枫糖浆、香草精，充分搅拌',
      '倒入布丁杯，放入冰箱冷藏至少4小时或过夜',
      '食用前撒上椰子片',
    ],
    isPremium: false,
  },
  // ===== 更多早餐 =====
  {
    id: '11',
    name: '皮蛋瘦肉粥',
    category: 'breakfast',
    imageUrl: '',
    calories: 260,
    protein: 16,
    carbs: 38,
    fat: 6,
    prepTime: 30,
    ingredients: [
      '大米 80g',
      '皮蛋 1个',
      '瘦肉丝 50g',
      '姜丝 适量',
      '葱花 适量',
      '盐 适量',
      '白胡椒粉 少许',
      '芝麻油 1茶匙',
    ],
    steps: [
      '大米淘洗后加水煮开，转小火熬20分钟',
      '皮蛋切丁，瘦肉丝用少许盐和淀粉腌制',
      '粥中加入姜丝、皮蛋丁煮5分钟',
      '放入肉丝搅散，煮至变色',
      '加盐和白胡椒粉调味',
      '撒葱花，淋芝麻油即可',
    ],
    isPremium: false,
  },
  {
    id: '12',
    name: '全麦鸡蛋三明治',
    category: 'breakfast',
    imageUrl: '',
    calories: 350,
    protein: 20,
    carbs: 38,
    fat: 12,
    prepTime: 10,
    ingredients: [
      '全麦吐司 2片',
      '鸡蛋 1个',
      '火腿片 2片',
      '生菜 2片',
      '番茄片 3片',
      '低脂芝士 1片',
      '蛋黄酱 1茶匙',
    ],
    steps: [
      '吐司烤至微焦',
      '鸡蛋煮熟或煎熟',
      '在一片吐司上依次放生菜、番茄片、火腿',
      '放上鸡蛋和芝士片',
      '盖上另一片吐司，沿对角线切开',
    ],
    isPremium: false,
  },
  {
    id: '13',
    name: '小笼包',
    category: 'breakfast',
    imageUrl: '',
    calories: 320,
    protein: 18,
    carbs: 36,
    fat: 12,
    prepTime: 40,
    ingredients: [
      '中筋面粉 200g',
      '猪肉馅 150g',
      '姜末 适量',
      '葱花 适量',
      '酱油 1汤匙',
      '料酒 1茶匙',
      '糖 少许',
      '盐 适量',
    ],
    steps: [
      '面粉加温水揉成光滑面团，醒发20分钟',
      '猪肉馅加入姜末、葱花、酱油、料酒、糖、盐搅匀',
      '面团搓条切小剂子，擀成薄皮',
      '包入肉馅，捏出褶皱',
      '蒸锅水开后放入小笼包，大火蒸8分钟',
      '配醋和姜丝食用',
    ],
    isPremium: false,
  },
  {
    id: '14',
    name: '蔬菜煎蛋饼',
    category: 'breakfast',
    imageUrl: '',
    calories: 230,
    protein: 14,
    carbs: 18,
    fat: 12,
    prepTime: 10,
    ingredients: [
      '鸡蛋 2个',
      '胡萝卜丝 30g',
      '西葫芦丝 30g',
      '葱花 适量',
      '面粉 2汤匙',
      '盐 适量',
      '食用油 1汤匙',
    ],
    steps: [
      '鸡蛋打散，加入面粉搅拌至无颗粒',
      '加入胡萝卜丝、西葫芦丝、葱花和盐搅匀',
      '平底锅刷油，倒入蛋糊摊平',
      '中小火煎至两面金黄',
      '卷起或切块装盘',
    ],
    isPremium: false,
  },
  {
    id: '15',
    name: '豆浆油条',
    category: 'breakfast',
    imageUrl: '',
    calories: 380,
    protein: 14,
    carbs: 42,
    fat: 16,
    prepTime: 15,
    ingredients: [
      '无糖豆浆 300ml',
      '油条 2根',
      '糖 适量（可选）',
    ],
    steps: [
      '豆浆加热至沸腾，转小火煮5分钟',
      '油条切段，放入烤箱180度复烤3分钟',
      '豆浆倒入碗中',
      '油条蘸豆浆食用',
    ],
    isPremium: false,
  },
  {
    id: '16',
    name: '牛油果吐司配水波蛋',
    category: 'breakfast',
    imageUrl: '',
    calories: 370,
    protein: 18,
    carbs: 30,
    fat: 20,
    prepTime: 12,
    ingredients: [
      '酸面包 2片',
      '牛油果 1/2个',
      '鸡蛋 1个',
      '柠檬汁 1茶匙',
      '红辣椒碎 适量',
      '盐和黑胡椒 适量',
    ],
    steps: [
      '面包烤至表面金黄',
      '牛油果加柠檬汁、盐和黑胡椒压成泥',
      '烧一锅水加少许白醋，水开后用筷子搅出漩涡',
      '打入鸡蛋煮2-3分钟至蛋白凝固',
      '面包抹上牛油果泥，放上水波蛋',
      '撒红辣椒碎和黑胡椒',
    ],
    isPremium: false,
  },
  {
    id: '17',
    name: '豆腐脑',
    category: 'breakfast',
    imageUrl: '',
    calories: 150,
    protein: 10,
    carbs: 12,
    fat: 7,
    prepTime: 15,
    ingredients: [
      '嫩豆腐 200g',
      '干木耳 5g',
      '干香菇 3朵',
      '鸡蛋 1个',
      '葱花 适量',
      '酱油 1汤匙',
      '水淀粉 2汤匙',
      '香油 1茶匙',
    ],
    steps: [
      '木耳和香菇泡发后切丝',
      '锅中加水烧开，放入木耳丝和香菇丝煮3分钟',
      '加入酱油调味，淋入水淀粉勾芡',
      '淋入蛋液搅成蛋花',
      '嫩豆腐盛入碗中，浇上卤汁',
      '撒葱花，淋香油',
    ],
    isPremium: false,
  },
  {
    id: '18',
    name: '小米粥配蒸饺',
    category: 'breakfast',
    imageUrl: '',
    calories: 340,
    protein: 14,
    carbs: 48,
    fat: 10,
    prepTime: 25,
    ingredients: [
      '小米 60g',
      '速冻蒸饺 6个',
      '枸杞 适量',
      '榨菜丝 适量',
    ],
    steps: [
      '小米淘洗后加水煮开，转小火熬20分钟',
      '蒸饺放入蒸锅，水开后蒸8分钟',
      '小米粥煮至粘稠，加入枸杞',
      '配榨菜丝和蒸饺一同食用',
    ],
    isPremium: false,
  },
  {
    id: '19',
    name: '法式吐司配水果',
    category: 'breakfast',
    imageUrl: '',
    calories: 330,
    protein: 14,
    carbs: 40,
    fat: 12,
    prepTime: 15,
    ingredients: [
      '厚切吐司 2片',
      '鸡蛋 1个',
      '牛奶 50ml',
      '肉桂粉 少许',
      '黄油 10g',
      '蜂蜜 1汤匙',
      '混合水果 80g',
    ],
    steps: [
      '鸡蛋打散加入牛奶和肉桂粉搅匀',
      '吐司浸入蛋液两面吸饱',
      '平底锅融化黄油，放入吐司中小火煎至两面金黄',
      '装盘放上水果，淋蜂蜜',
    ],
    isPremium: false,
  },
  {
    id: '20',
    name: '紫薯燕麦粥',
    category: 'breakfast',
    imageUrl: '',
    calories: 290,
    protein: 10,
    carbs: 52,
    fat: 5,
    prepTime: 20,
    ingredients: [
      '紫薯 150g',
      '燕麦片 40g',
      '牛奶 100ml',
      '核桃仁 15g',
      '红枣 3颗',
    ],
    steps: [
      '紫薯去皮切小块，蒸熟',
      '燕麦片加水煮3分钟',
      '紫薯用勺子压成泥',
      '将紫薯泥、燕麦粥、牛奶混合搅匀',
      '撒上核桃碎和红枣',
    ],
    isPremium: false,
  },
  // ===== 更多午餐 =====
  {
    id: '21',
    name: '红烧牛肉面',
    category: 'lunch',
    imageUrl: '',
    calories: 520,
    protein: 32,
    carbs: 58,
    fat: 16,
    prepTime: 60,
    ingredients: [
      '牛腩 200g',
      '面条 150g',
      '八角 2个',
      '桂皮 1小块',
      '生姜 3片',
      '生抽 2汤匙',
      '老抽 1汤匙',
      '冰糖 15g',
      '青菜 适量',
    ],
    steps: [
      '牛腩切块焯水去血沫',
      '锅中炒冰糖至焦糖色，放入牛腩翻炒上色',
      '加入姜片、八角、桂皮、生抽、老抽',
      '加水没过牛肉，大火烧开转小火炖1小时',
      '面条煮熟捞入碗中',
      '青菜焯水，与牛肉和汤一起浇在面上',
    ],
    isPremium: false,
  },
  {
    id: '22',
    name: '宫保鸡丁盖饭',
    category: 'lunch',
    imageUrl: '',
    calories: 480,
    protein: 30,
    carbs: 52,
    fat: 16,
    prepTime: 25,
    ingredients: [
      '鸡胸肉 150g',
      '花生米 30g',
      '干辣椒 5个',
      '花椒 1茶匙',
      '黄瓜丁 50g',
      '米饭 150g',
      '生抽 1汤匙',
      '醋 1汤匙',
      '糖 1茶匙',
    ],
    steps: [
      '鸡胸肉切丁，用料酒和淀粉腌制10分钟',
      '调酱汁：生抽、醋、糖、水淀粉混合',
      '花生米小火炒至金黄盛出',
      '锅中爆香干辣椒和花椒',
      '放入鸡丁翻炒至变色',
      '加入黄瓜丁和酱汁翻炒均匀',
      '撒花生米，配米饭食用',
    ],
    isPremium: false,
  },
  {
    id: '23',
    name: '青椒肉丝盖饭',
    category: 'lunch',
    imageUrl: '',
    calories: 450,
    protein: 26,
    carbs: 50,
    fat: 14,
    prepTime: 20,
    ingredients: [
      '猪里脊肉 100g',
      '青椒 2个',
      '胡萝卜丝 30g',
      '黑木耳 30g',
      '米饭 150g',
      '生抽 1汤匙',
      '淀粉 适量',
    ],
    steps: [
      '猪肉切丝，用生抽和淀粉腌制10分钟',
      '青椒切丝',
      '热锅凉油，滑炒肉丝至变色盛出',
      '锅中炒青椒丝和胡萝卜丝至断生',
      '放入肉丝和木耳翻炒均匀',
      '调味后配米饭食用',
    ],
    isPremium: false,
  },
  {
    id: '24',
    name: '番茄牛腩饭',
    category: 'lunch',
    imageUrl: '',
    calories: 500,
    protein: 28,
    carbs: 50,
    fat: 18,
    prepTime: 50,
    ingredients: [
      '牛腩 200g',
      '番茄 3个',
      '洋葱 半个',
      '番茄酱 1汤匙',
      '生姜 2片',
      '米饭 150g',
    ],
    steps: [
      '牛腩切块焯水',
      '番茄切块，洋葱切丝',
      '锅中炒洋葱至透明，加入番茄炒出汁',
      '放入牛腩、番茄酱和没过食材的水',
      '大火烧开转小火炖40分钟至牛腩软烂',
      '调味后配米饭食用',
    ],
    isPremium: false,
  },
  {
    id: '25',
    name: '鱼香肉丝饭',
    category: 'lunch',
    imageUrl: '',
    calories: 460,
    protein: 24,
    carbs: 54,
    fat: 15,
    prepTime: 20,
    ingredients: [
      '猪里脊 100g',
      '木耳 30g',
      '胡萝卜 50g',
      '青椒 30g',
      '泡椒 适量',
      '米饭 150g',
      '生抽、醋、糖、水淀粉 适量',
    ],
    steps: [
      '猪肉切丝，用淀粉和料酒腌制',
      '调鱼香汁：生抽、醋、糖、水淀粉混合',
      '胡萝卜、木耳、青椒切丝',
      '热锅炒肉丝至变色盛出',
      '爆香泡椒，炒胡萝卜丝和木耳丝',
      '放入肉丝和鱼香汁翻炒均匀',
    ],
    isPremium: false,
  },
  {
    id: '26',
    name: '咖喱鸡肉饭',
    category: 'lunch',
    imageUrl: '',
    calories: 510,
    protein: 28,
    carbs: 56,
    fat: 16,
    prepTime: 30,
    ingredients: [
      '鸡腿肉 150g',
      '土豆 1个',
      '胡萝卜 半根',
      '洋葱 半个',
      '咖喱块 2块',
      '米饭 150g',
      '食用油 适量',
    ],
    steps: [
      '鸡腿肉切块，土豆和胡萝卜切滚刀块，洋葱切块',
      '锅中炒洋葱至透明，加入鸡肉炒至变色',
      '加入土豆和胡萝卜翻炒2分钟',
      '加水没过食材，煮至土豆软烂',
      '关火加入咖喱块搅拌至融化',
      '小火煮至浓稠，配米饭食用',
    ],
    isPremium: false,
  },
  {
    id: '27',
    name: '蛋炒饭',
    category: 'lunch',
    imageUrl: '',
    calories: 420,
    protein: 18,
    carbs: 48,
    fat: 14,
    prepTime: 10,
    ingredients: [
      '隔夜米饭 200g',
      '鸡蛋 2个',
      '葱花 适量',
      '火腿丁 30g',
      '豌豆 30g',
      '盐 适量',
      '食用油 2汤匙',
    ],
    steps: [
      '鸡蛋打散，火腿切丁',
      '热锅倒油，炒鸡蛋至凝固盛出',
      '锅中再加油，放入米饭翻炒散开',
      '加入火腿丁和豌豆翻炒',
      '加入炒蛋和葱花翻炒均匀',
      '加盐调味即可',
    ],
    isPremium: false,
  },
  {
    id: '28',
    name: '番茄鸡蛋面',
    category: 'lunch',
    imageUrl: '',
    calories: 380,
    protein: 18,
    carbs: 48,
    fat: 12,
    prepTime: 20,
    ingredients: [
      '挂面 120g',
      '番茄 2个',
      '鸡蛋 2个',
      '葱花 适量',
      '盐 适量',
      '糖 少许',
      '食用油 1汤匙',
    ],
    steps: [
      '番茄切块，鸡蛋打散',
      '热锅炒鸡蛋至凝固盛出',
      '同一锅炒番茄至出汁，加少许糖',
      '加水烧开，放入挂面煮3分钟',
      '放入炒蛋，加盐调味',
      '撒葱花出锅',
    ],
    isPremium: false,
  },
  {
    id: '29',
    name: '麻辣香锅',
    category: 'lunch',
    imageUrl: '',
    calories: 480,
    protein: 28,
    carbs: 30,
    fat: 24,
    prepTime: 30,
    ingredients: [
      '虾仁 80g',
      '午餐肉 50g',
      '土豆片 50g',
      '藕片 50g',
      '西兰花 50g',
      '麻辣香锅底料 2汤匙',
      '蒜末 适量',
      '干辣椒 适量',
    ],
    steps: [
      '所有食材焯水或煎熟备用',
      '锅中加油，爆香蒜末和干辣椒',
      '加入麻辣香锅底料炒出红油',
      '放入所有食材大火翻炒均匀',
      '撒白芝麻和香菜出锅',
    ],
    isPremium: false,
  },
  {
    id: '30',
    name: '意大利肉酱面',
    category: 'lunch',
    imageUrl: '',
    calories: 490,
    protein: 24,
    carbs: 56,
    fat: 18,
    prepTime: 30,
    ingredients: [
      '意大利面 120g',
      '牛肉末 100g',
      '番茄罐头 200g',
      '洋葱 半个',
      '大蒜 2瓣',
      '橄榄油 1汤匙',
      '盐和黑胡椒 适量',
      '帕玛森芝士 适量',
    ],
    steps: [
      '意大利面加盐煮至al dente，沥干备用',
      '锅中加橄榄油，炒洋葱丁和蒜末至香',
      '加入牛肉末炒至变色',
      '倒入番茄罐头，小火煮15分钟',
      '加入煮好的意面拌匀',
      '撒帕玛森芝士和黑胡椒',
    ],
    isPremium: true,
  },
  // ===== 更多晚餐 =====
  {
    id: '31',
    name: '清蒸鲈鱼',
    category: 'dinner',
    imageUrl: '',
    calories: 320,
    protein: 40,
    carbs: 8,
    fat: 14,
    prepTime: 25,
    ingredients: [
      '鲈鱼 1条（约400g）',
      '姜丝 适量',
      '葱丝 适量',
      '蒸鱼豉油 2汤匙',
      '料酒 1汤匙',
      '食用油 1汤匙',
    ],
    steps: [
      '鲈鱼清洗干净，两面划几刀',
      '鱼身抹料酒，放上姜丝腌制10分钟',
      '蒸锅水开后放入鱼，大火蒸8-10分钟',
      '倒掉盘中蒸出的水',
      '铺上葱丝，淋蒸鱼豉油',
      '热油浇在葱丝上激出香味',
    ],
    isPremium: false,
  },
  {
    id: '32',
    name: '麻婆豆腐',
    category: 'dinner',
    imageUrl: '',
    calories: 280,
    protein: 18,
    carbs: 16,
    fat: 16,
    prepTime: 20,
    ingredients: [
      '嫩豆腐 300g',
      '猪肉末 50g',
      '豆瓣酱 1汤匙',
      '花椒粉 1茶匙',
      '辣椒面 1茶匙',
      '葱花 适量',
      '水淀粉 2汤匙',
    ],
    steps: [
      '豆腐切小块，焯水后沥干',
      '锅中炒肉末至变色',
      '加入豆瓣酱和辣椒面炒出红油',
      '加适量水烧开，轻轻放入豆腐',
      '中火煮5分钟入味',
      '淋水淀粉勾芡，撒花椒粉和葱花',
    ],
    isPremium: false,
  },
  {
    id: '33',
    name: '蒜蓉西兰花炒虾仁',
    category: 'dinner',
    imageUrl: '',
    calories: 260,
    protein: 30,
    carbs: 14,
    fat: 10,
    prepTime: 15,
    ingredients: [
      '虾仁 150g',
      '西兰花 200g',
      '蒜末 1汤匙',
      '盐 适量',
      '料酒 1茶匙',
      '食用油 1汤匙',
    ],
    steps: [
      '虾仁用料酒和少许盐腌制5分钟',
      '西兰花掰小朵，焯水1分钟',
      '热锅加油，爆香蒜末',
      '放入虾仁炒至变色',
      '加入西兰花翻炒均匀',
      '加盐调味即可',
    ],
    isPremium: false,
  },
  {
    id: '34',
    name: '番茄土豆炖牛腩',
    category: 'dinner',
    imageUrl: '',
    calories: 460,
    protein: 30,
    carbs: 36,
    fat: 20,
    prepTime: 60,
    ingredients: [
      '牛腩 250g',
      '番茄 2个',
      '土豆 1个',
      '胡萝卜 半根',
      '洋葱 半个',
      '番茄酱 1汤匙',
      '盐 适量',
    ],
    steps: [
      '牛腩切块焯水',
      '番茄、土豆、胡萝卜切块',
      '锅中炒洋葱和番茄至出汁',
      '加入牛腩、番茄酱和足量水',
      '炖40分钟后加入土豆和胡萝卜',
      '再炖15分钟至食材软烂，加盐调味',
    ],
    isPremium: false,
  },
  {
    id: '35',
    name: '冬瓜排骨汤',
    category: 'dinner',
    imageUrl: '',
    calories: 300,
    protein: 22,
    carbs: 12,
    fat: 18,
    prepTime: 50,
    ingredients: [
      '排骨 250g',
      '冬瓜 300g',
      '姜片 3片',
      '枸杞 适量',
      '盐 适量',
      '料酒 1汤匙',
    ],
    steps: [
      '排骨焯水去血沫',
      '锅中加足量水，放入排骨和姜片',
      '大火烧开转小火炖30分钟',
      '冬瓜去皮切块，放入锅中',
      '继续炖15分钟至冬瓜透明',
      '加盐和枸杞即可',
    ],
    isPremium: false,
  },
  {
    id: '36',
    name: '油醋汁考伯沙拉',
    category: 'dinner',
    imageUrl: '',
    calories: 350,
    protein: 28,
    carbs: 16,
    fat: 20,
    prepTime: 15,
    ingredients: [
      '鸡胸肉 100g',
      '生菜 100g',
      '牛油果 1/2个',
      '小番茄 50g',
      '水煮蛋 1个',
      '培根碎 20g',
      '油醋汁 2汤匙',
    ],
    steps: [
      '鸡胸肉煎熟切丁',
      '生菜撕碎铺底',
      '依次摆上鸡肉、牛油果块、小番茄对半切',
      '水煮蛋切瓣，放上培根碎',
      '淋油醋汁拌匀即可',
    ],
    isPremium: false,
  },
  {
    id: '37',
    name: '家常豆腐',
    category: 'dinner',
    imageUrl: '',
    calories: 300,
    protein: 18,
    carbs: 20,
    fat: 16,
    prepTime: 20,
    ingredients: [
      '老豆腐 300g',
      '木耳 30g',
      '青椒 1个',
      '胡萝卜片 30g',
      '生抽 1汤匙',
      '蚝油 1汤匙',
      '蒜末 适量',
    ],
    steps: [
      '豆腐切片，煎至两面金黄',
      '木耳泡发，青椒切块',
      '热锅爆香蒜末',
      '放入木耳、胡萝卜、青椒翻炒',
      '加入豆腐和酱汁轻轻翻炒',
      '加少许水焖2分钟入味',
    ],
    isPremium: false,
  },
  {
    id: '38',
    name: '白灼虾配时蔬',
    category: 'dinner',
    imageUrl: '',
    calories: 280,
    protein: 32,
    carbs: 12,
    fat: 10,
    prepTime: 15,
    ingredients: [
      '基围虾 200g',
      '姜片 3片',
      '葱段 适量',
      '生抽 1汤匙',
      '香油 1茶匙',
      '蒜蓉 适量',
      '芥兰 100g',
    ],
    steps: [
      '虾洗净去虾线',
      '锅中加水、姜片、葱段烧开',
      '放入虾煮至变红弯曲即捞出',
      '芥兰焯水摆盘',
      '调蘸料：生抽、香油、蒜蓉混合',
      '虾配蘸料食用',
    ],
    isPremium: false,
  },
  {
    id: '39',
    name: '菌菇豆腐汤',
    category: 'dinner',
    imageUrl: '',
    calories: 180,
    protein: 14,
    carbs: 16,
    fat: 8,
    prepTime: 20,
    ingredients: [
      '嫩豆腐 200g',
      '香菇 3朵',
      '金针菇 50g',
      '白玉菇 50g',
      '鸡蛋 1个',
      '葱花 适量',
      '盐 适量',
    ],
    steps: [
      '菌菇洗净，香菇切片，豆腐切小块',
      '锅中加油炒香菌菇',
      '加水烧开，放入豆腐煮5分钟',
      '淋入蛋液搅散',
      '加盐调味，撒葱花',
    ],
    isPremium: false,
  },
  {
    id: '40',
    name: '黑椒牛柳意面',
    category: 'dinner',
    imageUrl: '',
    calories: 480,
    protein: 32,
    carbs: 50,
    fat: 16,
    prepTime: 25,
    ingredients: [
      '牛肉条 120g',
      '意大利面 100g',
      '青椒丝 30g',
      '洋葱丝 30g',
      '黑胡椒酱 2汤匙',
      '黄油 10g',
    ],
    steps: [
      '牛肉条用料酒和黑胡椒腌制10分钟',
      '意面煮至al dente沥干',
      '黄油融化，煎牛肉条至七分熟盛出',
      '炒洋葱丝和青椒丝',
      '加入意面和黑胡椒酱翻炒',
      '放入牛肉条翻拌均匀',
    ],
    isPremium: true,
  },
  // ===== 更多零食 =====
  {
    id: '41',
    name: '希腊酸奶水果杯',
    category: 'snack',
    imageUrl: '',
    calories: 180,
    protein: 12,
    carbs: 24,
    fat: 5,
    prepTime: 5,
    ingredients: [
      '希腊酸奶 150g',
      '草莓 50g',
      '蓝莓 30g',
      '格兰诺拉 20g',
      '蜂蜜 1茶匙',
    ],
    steps: [
      '草莓切片',
      '杯中先铺一层酸奶',
      '铺一层水果和格兰诺拉',
      '重复分层至满',
      '淋蜂蜜即可',
    ],
    isPremium: false,
  },
  {
    id: '42',
    name: '烤红薯',
    category: 'snack',
    imageUrl: '',
    calories: 180,
    protein: 3,
    carbs: 40,
    fat: 1,
    prepTime: 45,
    ingredients: [
      '红薯 1个（约250g）',
    ],
    steps: [
      '红薯洗净擦干',
      '烤箱200度预热',
      '红薯放入烤箱烤40-45分钟',
      '烤至表皮焦黄、流出糖汁即可',
    ],
    isPremium: false,
  },
  {
    id: '43',
    name: '毛豆',
    category: 'snack',
    imageUrl: '',
    calories: 120,
    protein: 10,
    carbs: 10,
    fat: 5,
    prepTime: 15,
    ingredients: [
      '带壳毛豆 300g',
      '八角 2个',
      '盐 1汤匙',
      '花椒 1茶匙',
    ],
    steps: [
      '毛豆搓洗干净，剪去两头',
      '锅中加水、八角、花椒、盐烧开',
      '放入毛豆煮10分钟',
      '关火浸泡至冷却入味',
    ],
    isPremium: false,
  },
  {
    id: '44',
    name: '红枣枸杞银耳羹',
    category: 'snack',
    imageUrl: '',
    calories: 120,
    protein: 2,
    carbs: 26,
    fat: 0.5,
    prepTime: 30,
    ingredients: [
      '干银耳 10g',
      '红枣 5颗',
      '枸杞 适量',
      '冰糖 15g',
    ],
    steps: [
      '银耳泡发撕小朵',
      '银耳加水大火烧开转小火煮20分钟',
      '加入红枣和冰糖煮10分钟',
      '出锅前加入枸杞',
    ],
    isPremium: false,
  },
  {
    id: '45',
    name: '牛油果奶昔',
    category: 'snack',
    imageUrl: '',
    calories: 220,
    protein: 6,
    carbs: 24,
    fat: 12,
    prepTime: 5,
    ingredients: [
      '牛油果 1/2个',
      '牛奶 200ml',
      '蜂蜜 1汤匙',
      '冰块 适量',
    ],
    steps: [
      '牛油果取肉切块',
      '所有材料放入搅拌机',
      '搅拌至顺滑即可',
    ],
    isPremium: false,
  },
  {
    id: '46',
    name: '蒸玉米',
    category: 'snack',
    imageUrl: '',
    calories: 150,
    protein: 5,
    carbs: 32,
    fat: 2,
    prepTime: 20,
    ingredients: [
      '甜玉米 1根',
    ],
    steps: [
      '玉米剥去外皮，留最内一层',
      '蒸锅水开后放入玉米',
      '大火蒸15分钟',
      '趁热食用',
    ],
    isPremium: false,
  },
  {
    id: '47',
    name: '蔬菜棒配鹰嘴豆泥',
    category: 'snack',
    imageUrl: '',
    calories: 160,
    protein: 6,
    carbs: 18,
    fat: 8,
    prepTime: 10,
    ingredients: [
      '胡萝卜 1根',
      '黄瓜 半根',
      '芹菜 2根',
      '鹰嘴豆泥 3汤匙',
    ],
    steps: [
      '胡萝卜、黄瓜、芹菜切条',
      '蔬菜条摆盘',
      '配鹰嘴豆泥蘸食',
    ],
    isPremium: false,
  },
  {
    id: '48',
    name: '芒果椰奶西米露',
    category: 'snack',
    imageUrl: '',
    calories: 200,
    protein: 3,
    carbs: 34,
    fat: 6,
    prepTime: 30,
    ingredients: [
      '芒果 1个',
      '西米 30g',
      '椰奶 100ml',
      '牛奶 50ml',
      '糖 1汤匙',
    ],
    steps: [
      '西米煮至透明，过冷水沥干',
      '芒果去皮切丁',
      '椰奶、牛奶、糖混合搅匀',
      '杯中放西米、芒果丁，倒入椰奶',
    ],
    isPremium: false,
  },
]

export const exerciseSuggestions = [
  {
    type: 'cardio',
    name: '晨间慢跑',
    duration: 30,
    intensity: 'medium' as const,
    caloriesBurned: 250,
    description: '公园慢跑30分钟，保持舒适的有氧节奏',
  },
  {
    type: 'cardio',
    name: '高强度间歇跑',
    duration: 20,
    intensity: 'high' as const,
    caloriesBurned: 300,
    description: '1分钟冲刺+2分钟慢走交替，共6-8组',
  },
  {
    type: 'strength',
    name: '上肢力量训练',
    duration: 25,
    intensity: 'medium' as const,
    caloriesBurned: 180,
    description: '俯卧撑3组x12次，哑铃划船3组x12次，肩推3组x10次',
  },
  {
    type: 'strength',
    name: '下肢力量训练',
    duration: 30,
    intensity: 'high' as const,
    caloriesBurned: 260,
    description: '深蹲4组x12次，弓步3组x10次/腿，臀桥3组x15次',
  },
  {
    type: 'flexibility',
    name: '晨间瑜伽',
    duration: 20,
    intensity: 'low' as const,
    caloriesBurned: 90,
    description: '拜日式12轮，配合深呼吸',
  },
  {
    type: 'flexibility',
    name: '拉伸放松',
    duration: 15,
    intensity: 'low' as const,
    caloriesBurned: 50,
    description: '全身拉伸，重点放松腿部和背部',
  },
  {
    type: 'hiit',
    name: 'HIIT全身燃脂',
    duration: 25,
    intensity: 'high' as const,
    caloriesBurned: 350,
    description: '波比跳、开合跳、高抬腿等动作交替，每组45秒休息15秒',
  },
  {
    type: 'hiit',
    name: 'Tabata训练',
    duration: 16,
    intensity: 'high' as const,
    caloriesBurned: 280,
    description: '20秒极限运动+10秒休息，重复8轮',
  },
  {
    type: 'cardio',
    name: '游泳',
    duration: 40,
    intensity: 'medium' as const,
    caloriesBurned: 300,
    description: '自由泳和蛙泳交替，保持稳定配速',
  },
  {
    type: 'strength',
    name: '核心训练',
    duration: 20,
    intensity: 'medium' as const,
    caloriesBurned: 150,
    description: '平板支撑3组x45秒，卷腹3组x15次，俄罗斯转体3组x20次',
  },
]

export const weeklyExercisePlans = [
  {
    dayOfWeek: 1,
    exercises: [exerciseSuggestions[0], exerciseSuggestions[5]],
  },
  {
    dayOfWeek: 2,
    exercises: [exerciseSuggestions[2], exerciseSuggestions[9]],
  },
  {
    dayOfWeek: 3,
    exercises: [exerciseSuggestions[6]],
  },
  {
    dayOfWeek: 4,
    exercises: [exerciseSuggestions[3]],
  },
  {
    dayOfWeek: 5,
    exercises: [exerciseSuggestions[4], exerciseSuggestions[5]],
  },
  {
    dayOfWeek: 6,
    exercises: [exerciseSuggestions[1], exerciseSuggestions[7]],
  },
  {
    dayOfWeek: 0,
    exercises: [exerciseSuggestions[8], exerciseSuggestions[5]],
  },
]

export const healthTips = [
  '每天喝够2L水，可以有效提升新陈代谢约30%',
  '早餐在起床后1小时内进食，有助稳定血糖',
  '每餐先吃蔬菜再吃蛋白质，最后吃主食，有助于控制血糖',
  '保持7-8小时优质睡眠，睡眠不足会增加饥饿激素分泌',
  '饭前喝一杯水，可以自然减少进食量',
  '每周至少进行150分钟中等强度有氧运动',
  '多吃不同颜色的蔬菜水果，获取更全面的营养',
  '细嚼慢咽，每口饭咀嚼20-30次，给大脑足够时间接收饱腹信号',
  '减少加工食品摄入，尽量选择天然食材',
  '每天补充足够的蛋白质，每公斤体重约1.2-2.0g',
]

export const quickQuestions = [
  '我今天晚餐可以吃什么？',
  '减肥期间可以吃水果吗？',
  '运动后应该补充什么营养？',
  '如何提高基础代谢？',
  '推荐一份高蛋白早餐',
  '碳水循环饮食法适合我吗？',
]

export const dayNames = ['周日', '周一', '周二', '周三', '周四', '周五', '周六']
export const mealTypeNames = {
  breakfast: '早餐',
  lunch: '午餐',
  dinner: '晚餐',
  snack: '零食',
}
